import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local"
import { Electrolize } from "next/font/google";

const Electro = Electrolize({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--electro'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Electro.className}>{children}</body>
    </html>
  );
}

